server:
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${postgre.url}:${postgre.port}/${postgre.database}
    username: ${postgre.username}
    password: ${postgre.password}
  rabbitmq:
    host: ${rabbitmq.url}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

