version: '3.1'
services:
  db:
    container_name: 'postgres-order-manager'
    image: postgres:14.5-bullseye
    restart: 'on-failure'
    network_mode: 'host'
    environment:
      POSTGRES_PASSWORD: a1b2c3f4e5
      POSTGRES_USER: order_owner
      POSTGRES_DB: order_manager
  rabbit-mq:
    container_name: 'rabbitMQ-order-manager'
    image: rabbitmq:3.10.7-management
    restart: 'on-failure'
    network_mode: 'host'
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: order_owner
      RABBITMQ_DEFAULT_PASS: a1b2c3f4e5
  api-delivery-system:
    depends_on:
      - rabbit-mq
      - db
    container_name: 'api-delivery-system'
    image: marcianojosepaulo/api-delivery-system
    restart: 'on-failure'
    network_mode: 'host'
  websocket-delivery-system:
    depends_on:
      - coordinates-simulator
    container_name: 'websocket-delivery-system'
    image: marcianojosepaulo/websocket-delivery-system
    restart: 'on-failure'
    network_mode: 'host'
  front-delivery-system:
    container_name: 'front-delivery-system'
    image: marcianojosepaulo/front-delivery-system
    restart: 'on-failure'
    network_mode: 'host'
  coordinates-simulator:
    depends_on:
      - api-delivery-system
      - rabbit-mq
    container_name: 'coordinates-simulator'
    image: marcianojosepaulo/cordinates-simulator
    restart: 'always'
    network_mode: 'host'
