
CREATE TABLE ORDERS(
    ID VARCHAR(36) NOT NULL,
    ID_DRIVERS VARCHAR(36) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    STATUS INTEGER NOT NULL,
    DELIVERED_AT TIMESTAMP(6),
    CREATED_AT TIMESTAMP(6),
    UPDATED_AT TIMESTAMP(6),
    PRIMARY KEY (ID),
    CONSTRAINT FK_DRIVERS FOREIGN KEY(ID_DRIVERS) REFERENCES DRIVERS(ID)
);